[tool.poetry]
name = "machining-centers-analysis"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
uvicorn = "^0.54.0"
fastapi = "0.115.14"
sqlalchemy = "1.4.17"
psycopg2 = "2.9.11"
pydantic = "2.11.7"
passlib = "1.7.4"
python-jose = "3.5.0"
scikit-learn = "1.5.2"
pandas = "2.2.3"
numpy = "1.26.0"
python-dotenv = "1.2.2"
python-multipart = "0.0.20"
pytest = "8.4.1"
httpx = "0.28.1"
xgboost = "3.1.2"
catboost = "1.2.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
