# Stage 1: Сборка
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# RUN npm run build
# Пропускаем tsc (проверку типов) и запускаем только билд Vite
RUN npx vite build

# Stage 2: Раздача статики
FROM nginx:stable-alpine
# Копируем билд из первого этапа
COPY --from=build /app/dist /usr/share/nginx/html
# Копируем конфиг Nginx (важно для React Router)
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]